### PR TITLE
added img in blog post

### PR DESCRIPTION
**Pull request by Varsani2520**
added image in blog post

### CODE REVIEW

**Comment by singhJasvinder101** [comment]
Instead of images of each post you can show tags below with good styling otherwise images will not look good in mobile view

**Comment by Varsani2520** [comment]
Hey @singhJasvinder101 ,i change a code regarding your specification ,now you are ready to check it

**Comment by Varsani2520** [comment]
Hey @singhJasvinder101 , please add the label and merge it

**Comment by singhJasvinder101** [comment]
Hey @Varsani2520 The ui is not looking good 
image

**Comment by Varsani2520** [comment]
@singhJasvinder101 ,check it

**Comment by Varsani2520** [comment]
@singhJasvinder101 

i updated tags style as you said,
it's your responsibility to give response 

please check it and merge it
if you don't like it then inform me

**Comment by singhJasvinder101** [comment]
Still the same issue you have changed the CSS there must be 2 cards at same line
image


also you can use the 
tags.split(',').map(tag, idx => {tag})
using your own creativity is important

**Comment by Varsani2520** [comment]
Ok

**Comment by singhJasvinder101** [comment]
And instead of using random colours for background It will be good if you change text coloured of each tag and every implement this also  
review your code carefully remove comments and check the improvements in UI that you can made by your creativity

**Comment by singhJasvinder101** [comment]
here is example you can refer to show coloured tags
image

https://dev.to/hoverbaum/how-to-add-code-highlighting-to-your-devto-posts-2lp6

**Comment by Varsani2520** [comment]
@singhJasvinder101 

check this out,
image

i updated tags style with random colors and note that 'i used static blog'
you change with your dynamic blogs

**Comment by singhJasvinder101** [comment]
@Varsani2520 I have given all the instruction and specifications but the UI is not good enough to merge, so I am closing this pr

**Pull request closed without merging**
