### PR TITLE
Password constraints

### PR DESCRIPTION
**Pull request by AnanyaJain25**
Screenshot 2024-06-05 231126
Screenshot 2024-06-05 231237

MADE ALL THE NECESSARY CHANGES FOR ISSUE Display password constraints #62

### CODE REVIEW

**Comment by AnanyaJain25** [comment]
hey @singhJasvinder101  please review the PR all conflicts are resolved.

**Comment by AnanyaJain25** [comment]
hey @singhJasvinder101 ?

**Comment by AnanyaJain25** [comment]
hey @singhJasvinder101

**Comment by singhJasvinder101** [comment]
Hi @AnanyaJain25, I've been busy lately. 
I have a suggestion for your PR. I think you need to change the conflicting CSS for authentication pages. Also, for real-time red-labeled password errors, you can use toasts messages (make sure to use a good animated toast package) to display any constraints if there is something missing in the password. Show the message for those constraints concisely in one line.

**Comment by AnanyaJain25** [comment]
please check now @singhJasvinder101

**Comment by singhJasvinder101** [comment]
Have you run pull command to make your codebase updated as the password validation and other features not present in your code 
image

**Comment by singhJasvinder101** [comment]
duplicate lines also at login page you added forgot password which has not implemented yet
image

image

**Comment by AnanyaJain25** [comment]
hey @singhJasvinder101 can we connect on discord for the same

**Comment by singhJasvinder101** [comment]
@ananyaj25  https://discordapp.com/users/752543690425106522

**Pull request closed without merging**
