### PR TITLE
Adding Enhanced Readme

### PR DESCRIPTION
**Pull request by aasthakourav20**
Fixes: #14 
Added all the project details in the  Readme file 

Closes: #14

### CODE REVIEW

**Comment by aasthakourav20** [comment]
Hey @singhJasvinder101 , changes are done  . Kindly review

**Comment by aasthakourav20** [comment]
Hey @singhJasvinder101 , kindly review the changes .

**Comment by aasthakourav20** [comment]
> Hey @singhJasvinder101 , changes are done . Kindly review

Hey @singhJasvinder101 , Its been 2 days my pull request isn't accepted . Is there any issue with the PR please review the changes & in case of any issue  you can feel free for the changes

**Comment by singhJasvinder101** [comment]
Actually I was busy these day I will review all prs and issues tommorow

**Review by singhJasvinder101 — APPROVED** [review]

**Comment by aasthakourav20** [comment]
Hey @singhJasvinder101 , Kindly label this PR as level1, level2, level3 & GSSoC labels .

**Comment by aasthakourav20** [comment]
Hey @singhJasvinder101 , I can see that some link of this repository in Readme  aren't  working like Contributors images .
If you wish  I will  raise a new issue . I request you to please assign it to me .


image

**Comment by singhJasvinder101** [comment]
Reviewing your code is important the alignment was not good also the routing and links, I need to modified all things so carefully check your code before commit.

**Comment by aasthakourav20** [comment]
> Reviewing your code is important the alignment was not good also the routing and links, I need to modified all things so carefully check your code before commit.

Really sorry for the mistakes , I would take care for the next time .
I request can you please add labels to this PR !!

**Pull request merged**
