### PR TITLE
Added a scroll to top button

### PR DESCRIPTION
**Pull request by pani2004**
Issue #19

### CODE REVIEW

**Comment by singhJasvinder101** [comment]
The button for scroll to top is not visible , check it again if there is any bug

[bug.webm](https://github.com/singhJasvinder101/MyBlog/assets/131908922/7507420f-b4f1-49b5-be6e-edb9adac5df5)

**Comment by pani2004** [comment]
@singhJasvinder101 I had not added the scroll to top component to the blog specific page, done it now pls review it

**Comment by singhJasvinder101** [comment]
1) Alignment problem and it should above speeddial
2) Button is showing on in home pages not in blog description page

Screenshot_2024-05-30-17-40-00-164-edit_com android chrome
Screenshot_2024-05-30-17-39-42-218-edit_com android chrome

**Comment by pani2004** [comment]
@singhJasvinder101 pls review it now!!

**Comment by singhJasvinder101** [comment]
## You must review your code before commit and making pr 

## 1. bug in the post description page
image

## 2. alignment of top to scroll button still not fixed 
image

## 3. not visible for the lower screens 
image

**Pull request closed without merging**
