### PR TITLE
Implement Greeting on New Issues

### LINKED ISSUE #104: [FEATURE] Implement Greeting on New Issues
### Feature Description

Introduce a feature that automatically adds a greeting message to new issues created within the project's issue tracker.

### Use Case

This feature aims to enhance the initial interaction with contributors by providing a welcoming and informative message upon the creation of a new issue. Currently, new issues may lack context or guidance, leading to potential misunderstandings or delays in addressing the problem. By implementing a greeting message, we can establish clear communication from the outset and ensure that contributors feel supported and informed throughout the issue resolution process.

### Potential Solution

One potential solution is to create a customizable greeting message template that is automatically added to new issues upon creation. This template could include a brief welcome message, instructions for providing relevant information, and links to project resources or documentation. Additionally, the greeting message could encourage contributors to adhere to the project's issue reporting guidelines and provide any necessary context or details to expedite the resolution process.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
### Description

This pull request adds the feature to automatically greet users upon the creation of new issues within the project's issue tracker. It includes a customizable greeting message template to enhance initial interaction with contributors.

### Fixes

Fixes #104

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by singhJasvinder101** [comment]
you have added env secret name GITHUB_TOKEN 
image

**Comment by thevijayshankersharma** [comment]
> you have added env secret name GITHUB_TOKEN image

Yes

**Comment by singhJasvinder101** [comment]
will this env var work like I told you before that I am not able to add secret variables starting with GITHUB_*

**Comment by thevijayshankersharma** [comment]
yes it should work fine

**Comment by singhJasvinder101** [comment]
test it to see if it works

**Comment by thevijayshankersharma** [comment]
image

**Comment by thevijayshankersharma** [comment]
@singhJasvinder101 add labels please.

**Comment by singhJasvinder101** [comment]
should I add the same secret name of GITHUB_TOKEN to my own workflow for automated PR ?

**Comment by thevijayshankersharma** [comment]
> should I add the same secret name of GITHUB_TOKEN to my own workflow for automated PR ?

Yeah

**Comment by singhJasvinder101** [comment]
> @singhJasvinder101 add labels please.

label already added to issue #114

**Comment by thevijayshankersharma** [comment]
> > @singhJasvinder101 add labels please.
> 
> label already added to issue #114

It should be label to PRs.
Only labels with PRs get count

**Pull request merged**
