### PR TITLE
Added hovering animation on the cards  .

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I added the hovering animation on the cards when user hovers on the card then the card pops out with a light white shadow .
closes : #21 

https://github.com/singhJasvinder101/MyBlog/assets/118350936/87fbd505-4ce3-47c6-a8ff-411e7a04d15c

### CODE REVIEW

**Comment by singhJasvinder101** [comment]
Blue coloured hover glow will look cool With little more spread radius and increase by a pixel

**Comment by singhJasvinder101** [comment]
Use the primary colours used in the site like speed dial colour

**Comment by Ayushmaanagarwal1211** [comment]
I updated the color and size can you check it

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/singhJasvinder101/MyBlog/assets/118350936/a3a66c42-4660-4dab-880c-1ebe07e1e550

**Comment by Ayushmaanagarwal1211** [comment]
I Committed 1 pr for both issue the hovering animation and the backend validation . I checked thoroughly for all backend validations but if you find any bug please let me know i will solve that .

**Comment by singhJasvinder101** [comment]
Your backend code for email validation is quite complex you can exclude it from this pr, I will merge the card hovering animation.
I have concise way for email validation using regex I will push that shortly

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
Done

**Comment by singhJasvinder101** [comment]
Bro create new pr, It has taken 7 commits for the minor issue.

**Comment by Ayushmaanagarwal1211** [comment]
Done

**Comment by singhJasvinder101** [comment]
@Ayushmaanagarwal1211 you can also review the other issues and suggest them changes If they are ready to merge tag me I will verify and merge. I am also reviewing issues

**Comment by Ayushmaanagarwal1211** [comment]
Sure i will

**Comment by singhJasvinder101** [comment]
for hovering cards you need to create new pr with resolving errors

**Pull request closed without merging**
