### PR TITLE
 Implement Greeting on New Issues 

### LINKED ISSUE #104: [FEATURE] Implement Greeting on New Issues
### Feature Description

Introduce a feature that automatically adds a greeting message to new issues created within the project's issue tracker.

### Use Case

This feature aims to enhance the initial interaction with contributors by providing a welcoming and informative message upon the creation of a new issue. Currently, new issues may lack context or guidance, leading to potential misunderstandings or delays in addressing the problem. By implementing a greeting message, we can establish clear communication from the outset and ensure that contributors feel supported and informed throughout the issue resolution process.

### Potential Solution

One potential solution is to create a customizable greeting message template that is automatically added to new issues upon creation. This template could include a brief welcome message, instructions for providing relevant information, and links to project resources or documentation. Additionally, the greeting message could encourage contributors to adhere to the project's issue reporting guidelines and provide any necessary context or details to expedite the resolution process.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
### Description

This pull request adds the feature to automatically greet users upon the creation of new issues within the project's issue tracker. It includes a customizable greeting message template to enhance initial interaction with contributors.

### Fixes

Fixes #104

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by singhJasvinder101** [comment]
The issue is that I cannot add the "GITHUB_ACCESS" variable to the environment secret or to the environment variable.
image

**Comment by thevijayshankersharma** [comment]
@singhJasvinder101 try giving other name like "MY_REPO_ACCESS_TOKEN" .
I will update the code according to it.

**Comment by singhJasvinder101** [comment]
added you can update your code

**Comment by thevijayshankersharma** [comment]
There are many workflow I would like to add to your repo like auto comment on issue and PR close, on PR merge etc.

**Comment by singhJasvinder101** [comment]
Okay that's good, I have also added a workflow for managing PR, but it's not working because it's not accessing the environment variable properly. You can also make some changes if there are any other bugs in that. Additionally, feel free to add your own workflows

**Comment by thevijayshankersharma** [comment]
@singhJasvinder101 could you assign level label and gssoc label.

**Pull request merged**
