### PR TITLE
Added workflows

### LINKED ISSUE #109: [FEATURE] Enable Custom Workflows for Task Automation
### Feature Description

I am requesting the ability to create custom workflows within our project management system. These workflows would allow users to automate task transitions, notifications, and actions based on predefined conditions and triggers.

### Use Case

Currently, our team manually moves tasks through various stages of our project management process. This manual process is time-consuming and prone to errors, such as forgetting to notify stakeholders or update statuses. With custom workflows, we could automate these transitions. For example, when a task is marked as "In Progress," automatically notify the assigned team members. When a task is marked as "Complete," update related documentation and notify project stakeholders.

### Potential Solution

One potential solution would be to implement a visual workflow editor where users can define stages, transitions, and actions. This editor could allow for drag-and-drop functionality to create workflows, specify conditions (e.g., task status changes), and define actions (e.g., sending notifications, updating fields).

### Additional Context

This feature would significantly streamline our project management process, reduce errors, and improve overall efficiency. It would also ensure consistency in how tasks are handled across different projects and teams within our organization. Integrating this capability into our existing project management software would enhance its utility and make it a more powerful tool for managing complex projects effectively.

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
### Description

Adds functionality to create custom workflows within the project management system to automate task transitions, notifications, and actions based on predefined conditions and triggers.

Fixes #109

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### Screenshots (if applicable):

Add any screenshots of your changes, if applicable.

### CODE REVIEW

**Comment by thevijayshankersharma** [comment]
Do you have discord channel to talk ??

**Comment by thevijayshankersharma** [comment]
Add level 2 to it because level3 will not be considered for workflows.
And share the discord link if you have, I need guidance so that I can contribute in the code.

**Comment by singhJasvinder101** [comment]
> Add level 2 to it because level3 will not be considered for workflows. And share the discord link if you have, I need guidance so that I can contribute in the code.

https://discordapp.com/users/752543690425106522

**Comment by singhJasvinder101** [comment]
image

**Comment by thevijayshankersharma** [comment]
paste this code and check or should I raise new PR for it ??

name: Close Stale PRs

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  issues: write

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
  
    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR has been automatically closed due to inactivity from the owner for 30 days.'
        days-before-pr-stale: 30  # Adjusted to 30 days
        days-before-pr-close: 0
        exempt-pr-author: false
        exempt-pr-labels: ''
        only-labels: ''
        operations-per-run: 30
        remove-stale-when-updated: true
        debug-only: false

**Comment by thevijayshankersharma** [comment]
or else try this one 

```
name: Close PRs Without Linked Issues

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close_prs_without_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Use the desired Node.js version

      - name: Install dependencies
        run: npm install @actions/github  # Install required GitHub API library

      - name: Close PRs Without Linked Issues
        run: |
          const daysThreshold = 30;

          const github = require('@actions/github');

          async function closePRs() {
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            const owner = github.context.repo.owner;
            const repo = github.context.repo.repo;

            const { data: pullRequests } = await octokit.pulls.list({ owner, repo, state: 'open' });

            for (const pr of pullRequests) {
              const { data: issues } = await octokit.issues.listForRepo({ owner, repo, per_page: 100 });

              const linkedIssue = issues.find(issue =>
                issue.pull_request && issue.pull_request.url === pr.url
              );

              if (!linkedIssue) {
                await octokit.pulls.update({ owner, repo, pull_number: pr.number, state: 'closed' });
                await octokit.issues.createComment({
                  owner,
                  repo,
                  issue_number: pr.number,
                  body: "This pull request has been closed because it does not mention the issue that it solves. Please refer to the [Contributing files](https://github.com/Sulagna-Dutta-Roy/GGExtensions/blob/master/CONTRIBUTING.md) to help you add this information. Then, tag the maintainers so your PR can be reopened."
                });
              }
            }
          }

          closePRs();
```

**Comment by singhJasvinder101** [comment]
you can create new pr

**Comment by singhJasvinder101** [comment]
In the new issue, please include the following important points:

1) Check if the issue already exists before creating a new one.
2) Review your code carefully before making pull requests.
3) If there are any errors in the setup, please check the prerequisites and add your configuration to the environment variables in `.env` as provided in `.env.example`.

**Pull request merged**
