### PR TITLE
feature:Generate ai description for the post

### LINKED ISSUE #30: Feature:Enhance the post feature with Ai
# Feature Request: Introduce "Write with AI" Enhancement

## Description
We propose adding a "Write with AI" feature to our application. This functionality allows users to write a post and click a "Write with AI" button, which will then enhance the quality of their content.

## Details
- **Feature Name:** Write with AI
- **Purpose:** Enhance the quality of user-generated posts
- **Functionality:**
  - Users can write a post within the application.
  - After writing, users can click the "Write with AI" button.
  - The AI will process the content and enhance its quality, improving clarity, grammar, and overall effectiveness.
  
i will work on this

### PR DESCRIPTION
**Pull request by Sahilll15**
###closes #30 

### Feature: Generate Description with AI

This PR introduces a new feature that allows users to generate descriptions for their blog posts using AI. By entering a title, users can now automatically generate content for their posts with the help of an AI model integrated into the application.

### Key Changes:
- **New Button**: Added a "Generate With AI" button to the text editor interface.
- **AI Integration**: Implemented a backend API call to an AI service to generate content based on the provided title.
- **State Management**: Updated the state management to handle the AI-generated content.

### Process to Generate a Gemini API Key

1. **Sign Up / Log In to Gemini**:
    - Go to the [Gemini AI website](https://gemini-ai.com).
    - Sign up for a new account or log in if you already have one.

2. **Generate an API Key**:
    - Navigate to the API section of your account dashboard.
    - Click on "Generate API Key".
    - Copy the generated API key.

3. **Add the API Key to Your `.env` File**:
    - Open your project's `.env` file.
    - Add the following line, replacing `YOUR_GEMINI_API_KEY` with the API key you copied:

    ```env
    GEMINI_API=YOUR_GEMINI_API_KEY
    ```

### Usage

1. **Enter a Title**:
    - In the text editor, enter the title of your blog post.

2. **Generate Description**:
    - Click on the "Generate With AI" button.
    - The AI will generate content based on the provided title and display it in the editor.

### Notes
- The AI-generated content can be further edited manually if needed.

### Example Implementation
Screenshot 2024-05-30 at 9 06 00 PM

By following these steps, users can seamlessly integrate the AI content generation feature into their blog post creation workflow. This addition aims to enhance productivity and creativity by leveraging the power of AI.

### CODE REVIEW

**Comment by singhJasvinder101** [comment]
You have changed the port it may cause conflicting issues after merge for other contributors in development mode

Screenshot_2024-05-30-22-30-11-640-edit_com

**Review by singhJasvinder101 — APPROVED** [review]

**Comment by singhJasvinder101** [comment]
There is a problem with this feature in production I reviewed carefully now.
There is gateway error of API /ai with timeout of 13 ms and max timeout of netlify is of 10ms 

image

Checkout https://tech-stuffs.netlify.app/user/createPost
I have merged it by mistake

**Comment by Sahilll15** [comment]
> There is a problem with this feature in production I reviewed carefully now.
> 
> There is gateway error of API /ai with timeout of 13 ms and max timeout of netlify is of 10ms 
> 
> 
> 
> image
> 
> 
> 
> Checkout https://tech-stuffs.netlify.app/user/createPost
> 
> I have merged it by mistake
> 
> 

Okay i will look into it and make it a bit faster you can reopen the pr

**Comment by singhJasvinder101** [comment]
Is it open now ??
reopen pr option is not visible my side

**Comment by Sahilll15** [comment]
> Is it open now ?? reopen pr button is not visible my side

I am creating a new PR please merge that one

**Pull request merged**
