### PR TITLE
Added  Alerting popup #11

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
Added red text for all invalid behaviour at the time of clicking the submit button .
closes : #11

https://github.com/singhJasvinder101/MyBlog/assets/118350936/5b4c1117-2f1c-461b-945a-081b6af7c837

### CODE REVIEW

**Comment by singhJasvinder101** [comment]
@Ayushmaanagarwal1211 you must review your code before making pull request 

[bug.webm](https://github.com/singhJasvinder101/MyBlog/assets/131908922/797aa842-e1ca-4326-a4b9-60da2fc69cb3)

also you don't performed any of the work specified in issue point 1 of email validations and 2 password validations as done in the backend side

**Comment by Ayushmaanagarwal1211** [comment]
@singhJasvinder101  can you check it again i have given the checkValidity() condition as given in the original code to check all credentials are fine or not and i wanted to know like which password validation you want in issue 1 because backend just checking the length of the password .

**Comment by singhJasvinder101** [comment]
Ahh I see there is not validation of password at the backend side, now worries I will fix that If you want then you can also do 
but in the client side you can add validation checks for password 

1. Have more than 8 characters
2. Contains a capital letter
3. Contains a lowercase
4. Contains a number
5. Contains a uppercase

image

**Comment by Ayushmaanagarwal1211** [comment]
Ok so now for password i will use these validations :
1. Password must be greater than or equal to length 8
2. password must contain one special character (e.g., !, @, #, $, %, ^, &, *, (, )).
3. password must contain 1 numeric charachter 
4. One Upper Case charachter
And if you want any other validation please let me know 

And i want to ask one question is admin is also valid for email so i will also allow admin as valid email

**Comment by Ayushmaanagarwal1211** [comment]
and if you want i will also put backend validations for password after solving this issue

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
i did some changes you can check 

https://github.com/singhJasvinder101/MyBlog/assets/118350936/9d5868db-5692-4635-9800-5b2ac9ac3077

**Comment by Ayushmaanagarwal1211** [comment]
@singhJasvinder101 I did some changes and i tested it by giving many inputs but if you find any bug i will fix that .

**Review by singhJasvinder101 — APPROVED** [review]

**Comment by Ayushmaanagarwal1211** [comment]
Hii @singhJasvinder101 please put level and gssoc label

**Pull request merged**
