### PR TITLE
Added hovering animation on the cards .

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I added the hovering animation on the cards when user hovers on the card then the card pops out with a light white shadow .
closes : https://github.com/singhJasvinder101/MyBlog/issues/21

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
Hii @singhJasvinder101  can you please put gssoc and level label to be counted for leaderboard

**Comment by singhJasvinder101** [comment]
> Hii @singhJasvinder101 can you please put the gssoc and level label to be counted for the leaderboard

the issue is already labeled as gssoc

**Comment by Ayushmaanagarwal1211** [comment]
Actually PR should be labelled according to the maintainers please see

Screenshot 2024-06-03 193153

**Comment by Ayushmaanagarwal1211** [comment]
thnx for adding

**Pull request merged**
